myblog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  
  root "posts#index"
end

myblog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :body, presence: true
end

myblog/app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 3, message: "Too short to post!" }
  validates :body, presence: true

end

myblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
 

end

myblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all.order(created_at: "desc")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render "new"
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render "edit"
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

myblog/app/helpers/comments_helper.rb
module CommentsHelper
end

myblog/app/helpers/posts_helper.rb
module PostsHelper
end

myblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <h1><%= link_to image_tag('logo.png', class: 'logo'), root_path %></h1>
    <%= yield %>
    </div>
  </body>
</html>

myblog/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <p>
  <%= f.text_field :title, placeholder: "enter title" %>
  <% if @post.errors.messages[:title].any? %>
    <span class="error"><%= @post.errors.messages[:title][0] %></span>
  <% end %>
  </p>
  <p>
  <%= f.text_area :body, placeholder: "enter body text" %>
  <% if @post.errors.messages[:body].any? %>
    <span class="error"><%= @post.errors.messages[:body][0] %></span>
  <% end %>
  </p>
  <p>
  <%= f.submit %>
  </p>
<% end %>

myblog/app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<%= render "form" %>

myblog/app/views/posts/index.html.erb
<h2>
  <%= link_to "Add New", new_post_path, class: "header-menu" %>
  My Posts
</h2>
<ul>
<% @posts.each do |post| %>
  <li><%= link_to post.title, post_path(post) %>
      <%= link_to "[Edit]", edit_post_path(post), class: "command" %>
      <%= link_to "[x]", 
        post_path(post), 
        method: :delete,
        class: "command",
        data: {confirm: "Sure?" }%></li>
<% end %>
</ul>

myblog/app/views/posts/new.html.erb
<h2>Add New Post</h2>
<%= render "form" %>

myblog/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= simple_format @post.body %></p>
<h3>Comments</h3>
<% if @post.comments.any? %>
  <ul>
  <% @post.comments.each do |comment| %>
    <li>
    <%= comment.body %>
    <%= link_to "[x]", 
      post_comment_path(@post, comment), 
      method: :delete,
      class: "command",
      data: {confirm: "Sure?" } %>
    </li>
  <% end %>
  </ul>
<% end %>
<%= form_for ([@post, @post.comments.build]) do |f| %>
  <p>
  <%= f.text_field :body %>
  </p>
  <p>
  <%= f.submit %>
  </p>
<% end %>